project:
  type: book

book:
  title: "Cultural Evolution and Music"
  subtitle: "Models and Applications in Python"
  author: 
    - name: "Fabian C. Moss"
      url: https://www.fabian-moss.de
      affiliation: University of Amsterdam
      affiliation-url: https://www.uva.nl/profiel/m/o/f.c.moss/f.c.moss.html
  date: "9 August 2022"
  chapters:
    - index.qmd
    - intro.qmd
    - style.qmd
    - python_primer.qmd
    # - summary.qmd
    - part: Cultural inheritence mechanisms
      chapters:
        - chapter03.qmd
        - chapter04.qmd
        - chapter05.qmd
        - chapter06.qmd
        - chapter07.qmd
        - chapter08.qmd
        - chapter09.qmd
    - part: Advanced topics
      chapters:
        - advanced.qmd
    - conclusion.qmd
    - references.qmd
  cover-image: texture.jpg # Photo by <a href="https://unsplash.com/@ascales?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Alan Scales</a> on <a href="https://unsplash.com/s/photos/a4-texture?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  page-footer: 
    left: "Copyright 2022, Fabian C. Moss" 
    right: 
      - icon: github
        href: https://github.com/fabianmoss
      - icon: twitter 
        href: https://twitter.com/fabianmoss
    border: true
    background: dark
  
execute:
  freeze: auto  # re-render only when source changes

citation:
  url: https://fabianmoss.github.io/cultevopy
bibliography: references.bib
csl: apa.csl

appendix-style: default

warning: false # turn off warnings (important for PDF output)

website:
  cookie-consent: true
  style: simple

format:
  html:
    theme: journal # cosmo
  pdf:
    template: eisvogel.tex
    titlepage: true
    titlepage-background: texture.jpg
    titlepage-text-color: ffffff
    ### see here for template customization possibilities: https://github.com/Wandmalfarbe/pandoc-latex-template
    # documentclass: scrreprt
    papersize: a4paper
    highlight-style: github
    include-before-body: empty.tex

license: "CC BY-NC"
