project:
  type: book

book:
  title: "Music Memes" 
  subtitle: "Understanding music transmission processes through cultural evolution modeling"
  author: 
    - name: "Fabian C. Moss"
      url: https://www.fabian-moss.de/
      affiliation: Julius-Maximilians-Universität Würzburg, Germany
      affiliation-url: https://www.musikwissenschaft.uni-wuerzburg.de/team/moss/
  date: "14 February 2023"
  chapters:
    - index.qmd
    - part: Prelude
      chapters: 
      - intro.qmd
      - style.qmd
      - python_primer.qmd
      - randomness.qmd
      - models.qmd
    - part: Foundations
      chapters:
        - chapter03.qmd
        - chapter04.qmd
        - biased_mutation.qmd
    - part: Modeling biases
      chapters:
        - chapter05.qmd
        - chapter06.qmd
        - chapter07.qmd
        - chapter08.qmd
        - chapter09.qmd
    - part: Advanced topics
      chapters:
        # - document_traditions.qmd
        - pitches.qmd
        - folk_tunes.qmd
        - communities.qmd
        - style_evolution.qmd
    - conclusion.qmd
    # - appendix.qmd
    - references.qmd
  cover-image: texture.jpg # Photo by <a href="https://unsplash.com/@ascales?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Alan Scales</a> on <a href="https://unsplash.com/s/photos/a4-texture?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  page-footer: 
    left: "Copyright 2024, Fabian C. Moss" 
    right: 
      - icon: github
        href: https://github.com/fabianmoss
      - icon: twitter 
        href: https://twitter.com/fabianmoss
    border: true
    background: dark
  
execute:
  freeze: auto  # re-render only when source changes

citation:
  url: https://fabianmoss.github.io/musicmemes
bibliography: references.bib
csl: apa.csl

appendix-style: default

warning: false # turn off warnings (important for PDF output)

# website:
#   cookie-consent: true
#   style: simple

format:
  html:
    theme: journal # cosmo
  pdf:
    template: eisvogel.tex
    titlepage: true
    titlepage-background: texture.jpg
    titlepage-text-color: ffffff
    ### see here for template customization possibilities: https://github.com/Wandmalfarbe/pandoc-latex-template
    # documentclass: scrreprt
    papersize: a4paper
    # highlight-style: light
    # include-before-body: empty.tex
    code-line-numbers: true
    highlight-style: dracula
    code-block-bg: f5f5f5
    cite-method: biblatex

license: "CC BY-NC"
