project:
  type: book

book:
  title: "Cultural Evolution and Music"
  subtitle: "Models and Applications in Python"
  author: "Fabian C. Moss"
  date: "8/8/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter00.qmd # Python Primer
    # - summary.qmd
    - part: Basics
      chapters:
        - chapter01.qmd
        - chapter02.qmd
        - chapter03.qmd
        - chapter04.qmd
        - chapter05.qmd
      # - chapter06.qmd
    - part: "Advanced topics"
      chapters:
        - advanced.qmd
    - references.qmd
  cover-image: texture.jpg # Photo by <a href="https://unsplash.com/@jazminantoinette?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jazmin Quaynor</a> on <a href="https://unsplash.com/s/photos/texture?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



